server.port=8083
spring.application.name=inventory-service

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/flashbuy
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Inventory Specific
inventory.flash-sale.stock-limit=100
