server.port=8082
spring.application.name=cart-service

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Resilience: Continue if Redis is down
spring.data.redis.repositories.enabled=false
spring.cache.type=none

# TTL for Carts (e.g., 1 hour)
cart.ttl.seconds=3600
