server.port=8081
spring.application.name=catalog-service

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/flashbuy
spring.datasource.username=admin
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
