server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: 6379
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 500
            redis-rate-limiter.burstCapacity: 1000
            redis-rate-limiter.requestedTokens: 1
        - name: CircuitBreaker
          args:
            name: mainCircuitBreaker
            fallbackUri: forward:/fallback/message
      routes:
        - id: catalog-service
          uri: ${CATALOG_SERVICE_URL:http://catalog-service:8081}
          predicates:
            - Path=/api/catalog/**
        
        - id: cart-service
          uri: ${CART_SERVICE_URL:http://cart-service:8082}
          predicates:
            - Path=/api/cart/**

        - id: inventory-service
          uri: ${INVENTORY_SERVICE_URL:http://inventory-service:8083}
          predicates:
            - Path=/api/inventory/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL:http://order-service:8084}
          predicates:
            - Path=/api/orders/**

        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://payment-service:8085}
          predicates:
            - Path=/api/payments/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    prometheus:
      enabled: true
    gateway:
      enabled: true
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        slowCallDurationThreshold: 3s
        slowCallRateThreshold: 50
        registerHealthIndicator: true
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - java.io.IOException
          - org.springframework.cloud.gateway.support.NotFoundException
